### ISSUE TITLE
🐛 The admin panel text is blocked by images

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/MindLogger-bug-reports#52]
When refreshing applets in the api admin panel, there are images blocking the text at top.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

![Screen Shot 2019-11-26 at 12 07 33 PM](https://user-images.githubusercontent.com/236532/69656001-b4c7c400-1045-11ea-88a1-c8c69a71581f.png)

**Comment by shnizzedy** [comment]
@binarybottle what text do you expect? The one I set up shows the `skos:prefLabel` and `schema:description` of the protocol under the image and above the buttons.

![HBN EMA card](https://user-images.githubusercontent.com/5974438/69657631-9f07ce00-1048-11ea-90f7-decabd2a2db0.png)

**Comment by henryrossiter** [comment]
I've also experienced the same behavior as @binarybottle occasionally. I haven't looked too far into it but I suspect it may be related to outdated schemas.

**Comment by henryrossiter** [comment]
The applets that aren't loading correctly seem to be missing some info. When I log on to the admin panel with an old account and add a new applet only the new applet renders properly:

**Comment by shnizzedy** [comment]
@henryrossiter I think you're right on with your diagnosis. `5d9df358ad53a828f89285d4` is using the protocol `https://raw.githubusercontent.com/henryrossiter/MindLoggerActivitySets/master/ActivitySets/video_test/video_schema` but that applet is in an old enough format that it calls it an `activitySet` instead of an applet, and that format is no longer supported.
Reimporting that same protocol, I get this: 
![reimported card](https://user-images.githubusercontent.com/5974438/69675329-5e21b080-106c-11ea-8f2f-84320e3fb27c.png)
